import '../../models/achievement.dart';

class AchievementsRegistry {
  static const List<Achievement> allAchievements = [
    Achievement(
      id: 'first_victory',
      title: 'First Victory',
      description: 'Win your first game in LetterLoom.',
      iconName: '🏆',
      targetValue: 1,
      xpReward: 100,
    ),
    Achievement(
      id: 'first_bingo',
      title: 'First Bingo',
      description: 'Use all seven rack tiles in a single turn.',
      iconName: '⚡',
      targetValue: 1,
      xpReward: 150,
    ),
    Achievement(
      id: 'hard_earned',
      title: 'Hard Earned',
      description: 'Defeat the Hard computer opponent.',
      iconName: '🥊',
      targetValue: 1,
      xpReward: 200,
    ),
    Achievement(
      id: 'big_move',
      title: 'Big Move',
      description: 'Score at least 50 points in a single turn.',
      iconName: '🔥',
      targetValue: 1,
      xpReward: 100,
    ),
    Achievement(
      id: 'triple_century',
      title: 'Triple Century',
      description: 'Score at least 300 points in one game.',
      iconName: '💯',
      targetValue: 1,
      xpReward: 200,
    ),
    Achievement(
      id: 'wordsmith',
      title: 'Wordsmith',
      description: 'Play 50 valid words.',
      iconName: '📚',
      targetValue: 50,
      xpReward: 150,
    ),
    Achievement(
      id: 'winning_streak',
      title: 'Winning Streak',
      description: 'Win 5 games consecutively.',
      iconName: '👑',
      targetValue: 5,
      xpReward: 250,
    ),
    Achievement(
      id: 'veteran',
      title: 'Veteran',
      description: 'Complete 50 total games.',
      iconName: '🎖️',
      targetValue: 50,
      xpReward: 300,
    ),
    Achievement(
      id: 'champion',
      title: 'Champion',
      description: 'Win 50 games.',
      iconName: '🥇',
      targetValue: 50,
      xpReward: 500,
    ),
    Achievement(
      id: 'century_champion',
      title: 'Century Champion',
      description: 'Win 100 games.',
      iconName: '🌟',
      targetValue: 100,
      xpReward: 1000,
    ),
    Achievement(
      id: 'close_call',
      title: 'Close Call',
      description: 'Win a game by a margin of 5 points or less.',
      iconName: '🎯',
      targetValue: 1,
      xpReward: 150,
    ),
    Achievement(
      id: 'comeback',
      title: 'Comeback',
      description: 'Win a game after trailing by at least 30 points.',
      iconName: '🏹',
      targetValue: 1,
      xpReward: 200,
    ),
    Achievement(
      id: 'seven_day_streak',
      title: 'Seven-Day Streak',
      description: 'Maintain a 7-day engagement streak.',
      iconName: '📅',
      targetValue: 7,
      xpReward: 250,
    ),
    Achievement(
      id: 'ranked_debut',
      title: 'Ranked Debut',
      description: 'Complete your first Ranked multiplayer game.',
      iconName: '⚔️',
      targetValue: 1,
      xpReward: 150,
    ),
    Achievement(
      id: 'moving_up',
      title: 'Moving Up',
      description: 'Earn your first Ranked promotion.',
      iconName: '📈',
      targetValue: 1,
      xpReward: 200,
    ),
    Achievement(
      id: 'bingo_master',
      title: 'Bingo Master',
      description: 'Play 10 Bingos over time.',
      iconName: '💥',
      targetValue: 10,
      xpReward: 300,
    ),
  ];
}
